apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener-flyway
spec:
  #serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: gh-trigger
      interceptors:
        - github:
            #secretRef:
            #  secretName: foo
            #  secretKey: bar
            eventTypes:
              - push
              - ping
      #bindings:
      #  - name: pipeline-binding-asdf
      template:
        name: flyway-container-build