#       Copyright 2017-2019 IBM Corp All Rights Reserved

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: container-build-push
spec:
  workspaces:
  - name: pipeline
    description: The workspace containing the source Dockerfile
  inputs:
    params:
    - name: dockerfile
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: context
      description: The build context used by Kaniko.
      default: ./
    - name: imageUrl
      description: The destination tag to store the image
    - name: context
      description: Path within the workspace to find the Dockerfile
    - name: sourceDir
      description: defines the directory where the source can be found
      type: string
    - name: extraArgs
      description: Additional arguments to pass to the Kaniko executor
      default: ""
  steps:
  - name: debug
    image: alpine:latest
    script: |
        ls -la $(inputs.params.sourceDir)/$(inputs.params.context)
        cd $(inputs.params.sourceDir)/$(inputs.params.context)
        cat $(inputs.params.dockerfile)
        echo "Extra args: $(inputs.params.extraArgs)"
  - name: container-build-push
    workingdir: "$(inputs.params.sourceDir)/"
    image: gcr.io/kaniko-project/executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    command:
    - /kaniko/executor
    - $(inputs.params.extraArgs)
    - --skip-tls-verify
    - --dockerfile=$(inputs.params.dockerfile)
    - --context=$(inputs.params.sourceDir)/$(inputs.params.context)
    - --destination=$(inputs.params.imageUrl)
    securityContext:
      runAsUser: 0
