#       Copyright 2017-2019 IBM Corp All Rights Reserved

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: init-pipeline
spec:
  inputs:
    params:
    - name: uid
      type: string
      description: Unique build Uid
  workspaces:
  - name: pipeline
  results:
  - name: sourceDir
    description: The directory containing the source code
  - name: artefactDir
    description: The directory containing the build artefacts
  - name: imageUrl
    description: The output image url
  steps:
  - name: set-directories
    image: alpine:latest
    script: |
      echo "$(inputs.params.uid)"
      mkdir "$(workspaces.pipeline.path)/dummyUid"
      mkdir "$(workspaces.pipeline.path)/dummyUid/source"
      mkdir "$(workspaces.pipeline.path)/dummyUid/artefacts"
      echo -n "$(workspaces.pipeline.path)/dummyUid/source" > /tekton/results/sourceDir
      echo -n "$(workspaces.pipeline.path)/dummyUid/artefacts" > /tekton/results/artefactDir
      ls -la "$(workspaces.pipeline.path)/"
      ls -la "$(workspaces.pipeline.path)/dummyUid/"
    securityContext:
      runAsUser: 0