#       Copyright 2017-2019 IBM Corp All Rights Reserved

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: container-build-push
spec:
  workspaces:
  - name: source
    description: The workspace containing the source Dockerfile
  inputs:
    params:
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: CONTEXT
      description: The build context used by Kaniko.
      default: ./
    - name: BUILT_IMAGE
      description: The destination tag to store the image
#    resources:
#    - name: source
#      type: git
#  outputs:
#    resources:
#      - name: builtImage
#        type: image
  steps:
  - name: container-build-push
    workingdir: "$(workspaces.source.path)/src"
    image: gcr.io/kaniko-project/executor:v0.13.0
    # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
    # https://github.com/tektoncd/pipeline/pull/706
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    command:
    - /kaniko/executor
    #- $(inputs.params.EXTRA_ARGS)
    - --skip-tls-verify
    - --dockerfile=$(inputs.params.DOCKERFILE)
    - --context="$(workspaces.source.path)/src/$(inputs.params.CONTEXT)"  # The user does not need to care the workspace and the source.
    - --destination=$(inputs.params.BUILT_IMAGE)
    securityContext:
      runAsUser: 0
