apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-binding
spec:
  params:
  - name: gitRevision
    value: $(body.head_commit.id)
  - name: gitUrl
    value: $(body.repository.ssh_url)
  - name: gitRepoName
    value: $(body.repository.name)
  #- name: gitBranchName
  #  value: $(body.repository.branch)
  #- name: contentType
  #  value: $(header.content-type)