apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-provisioning-binding
subjects:
- kind: ServiceAccount
  name: service-deploy
roleRef:
  kind: Role
  name: service-provisioning