apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-trigger-minimal-binding
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: tekton-triggers-minimal